version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: k1core_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_broker
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: django_fastapi
    depends_on:
      - db
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: "K1core.settings"
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  celery_worker:
    build: .
    container_name: celery_worker
    depends_on:
      - db
      - redis
    command: celery -A K1core worker --loglevel=info
    environment:
      DJANGO_SETTINGS_MODULE: "K1core.settings"
    volumes:
      - .:/app

  celery_beat:
    build: .
    container_name: celery_beat
    depends_on:
      - db
      - redis
    command: celery -A K1core beat --loglevel=info
    environment:
      DJANGO_SETTINGS_MODULE: "K1core.settings"
    volumes:
      - .:/app

volumes:
  postgres_data:
